`timescale 1ns/1ps

// ============================================================
// Matrix Multiplication Demo  —  Auto-generated by run_matrix_multiply.py
// C = A x B
// A: 2x4   B: 4x2   C: 2x2
//
// Shared-memory layout:
//   A  :  addresses 0 .. 7
//   B  :  addresses 8 .. 15
//   C  :  addresses 16 .. 19
//
// Parallel execution:  8 GPU cores
//   Cores 0-3  compute one row of C  (row r0)
//   Cores 4-7  compute next row of C (row r1, if it exists)
//   Two rows are therefore computed simultaneously per batch.
// ============================================================

module matrix_multiply_demo;

    localparam M = 2;  // rows of A
    localparam K = 4;  // cols of A / rows of B
    localparam N = 2;  // cols of B

    localparam A_BASE = 0;
    localparam B_BASE = 8;
    localparam C_BASE = 16;

    reg clk, reset;
    initial clk = 0;
    always #5 clk = ~clk;

    // ── GPU top interface ─────────────────────────────────────
    reg        start;
    reg [15:0] instruction_in;
    reg        instr_valid_in;
    reg [1:0]  acc_ctrl_in;
    reg [7:0]  load_en_bus;
    reg [3:0]  load_addr;
    reg [7:0]  load_data_bus [0:7];

    wire        instr_advance;
    wire        gpu_done;
    wire [7:0]  result_bus   [0:7];
    wire [7:0]  acc_bus      [0:7];
    wire [7:0]  mul_high_bus [0:7];
    wire [7:0]  zero_bus, carry_bus;
    wire [7:0]  negative_bus, overflow_bus;
    wire [7:0]  div_done_bus, div_by_zero_bus;

    gpu_top dut(
        .clk(clk), .reset(reset),
        .start(start), .done(gpu_done),
        .instruction_in(instruction_in),
        .instr_valid_in(instr_valid_in),
        .acc_ctrl_in(acc_ctrl_in),
        .instr_advance(instr_advance),
        .load_en_bus(load_en_bus),
        .load_addr(load_addr),
        .load_data_bus(load_data_bus),
        .result_bus(result_bus),
        .acc_bus(acc_bus),
        .mul_high_bus(mul_high_bus),
        .zero_bus(zero_bus),
        .carry_bus(carry_bus),
        .negative_bus(negative_bus),
        .overflow_bus(overflow_bus),
        .div_done_bus(div_done_bus),
        .div_by_zero_bus(div_by_zero_bus)
    );

    // ── Shared memory ─────────────────────────────────────────
    reg [7:0]  sm_write_en_bus;
    reg [5:0]  sm_write_addr [0:7];
    reg [7:0]  sm_write_data [0:7];
    reg [5:0]  sm_read_addr  [0:7];
    wire [7:0] sm_read_data  [0:7];
    wire       sm_conflict;
    wire [2:0] sm_winner;

    shared_memory sm(
        .clk(clk), .reset(reset),
        .write_en_bus(sm_write_en_bus),
        .write_addr_bus(sm_write_addr),
        .write_data_bus(sm_write_data),
        .read_addr(sm_read_addr),
        .read_data(sm_read_data),
        .write_conflict(sm_conflict),
        .write_winner(sm_winner)
    );

    // ── Matrix storage ────────────────────────────────────────
    reg [7:0] mat_a [0:1][0:3];
    reg [7:0] mat_b [0:3][0:1];
    reg [7:0] mat_c [0:1][0:1];
    reg [7:0] ref_c [0:1][0:1];

    integer file_handle;
    integer i, j, k;
    integer t_start, t_end, total_cycles;

    // ── Task: load one value into every core's register ───────
    task load_all;
        input [3:0] addr;
        input [7:0] d0, d1, d2, d3, d4, d5, d6, d7;
        begin
            load_addr        = addr;
            load_data_bus[0] = d0; load_data_bus[1] = d1;
            load_data_bus[2] = d2; load_data_bus[3] = d3;
            load_data_bus[4] = d4; load_data_bus[5] = d5;
            load_data_bus[6] = d6; load_data_bus[7] = d7;
            load_en_bus      = 8'hFF;
            instr_valid_in   = 0;
            @(posedge clk);
            load_en_bus = 8'h00;
            @(posedge clk);
        end
    endtask

    // ── Task: dispatch one instruction to all cores ───────────
    task run_one_instr;
        input [15:0] instr;
        input [1:0]  acc_mode;
        begin
            instruction_in = instr;
            acc_ctrl_in    = acc_mode;
            instr_valid_in = 1;
            @(negedge clk); start = 1;
            @(negedge clk); start = 0;
            repeat(10000) begin
                @(negedge clk);
                if (instr_advance) begin
                    instr_valid_in = 0;
                    acc_ctrl_in    = 2'b00;
                end
                if (gpu_done) disable run_one_instr;
            end
        end
    endtask

    // ── Task: write one byte into shared memory via core 0 ────
    task sm_write;
        input [5:0] addr;
        input [7:0] data;
        begin
            sm_write_en_bus  = 8'h01;
            sm_write_addr[0] = addr;
            sm_write_data[0] = data;
            @(posedge clk);
            sm_write_en_bus = 8'h00;
            @(posedge clk);
        end
    endtask

    // ── Task: compute two rows of C in parallel ───────────────
    //
    // Cores 0-3 compute C[r0][0..N-1]
    // Cores 4-7 compute C[r1][0..N-1]  (skipped when r1 == -1)
    //
    // For each accumulation term k:
    //   1. Load A[r0][k] into reg-0 of cores 0-3
    //      Load A[r1][k] into reg-0 of cores 4-7  (or 0 if r1 invalid)
    //   2. Load B[k][col] into reg-1 of each core
    //      Core c gets B[k][ col(c) ] where col(c) = c mod N
    //   3. Execute MUL-ACC instruction
    //
    task compute_rows;
        input integer r0;
        input integer r1;   // pass -1 if no second row
        integer acc_term;
        integer ci;
        begin
            // Clear accumulators in all cores
            @(posedge clk);
            acc_ctrl_in = 2'b11;
            @(posedge clk);
            acc_ctrl_in = 2'b00;

            for (acc_term = 0; acc_term < 4; acc_term = acc_term + 1) begin

                // ── Step 1: load A elements ───────────────────
                // All four cores in each group get the same A[row][k]
                sm_read_addr[0] = 0 + r0*4 + acc_term;
                sm_read_addr[1] = 0 + r0*4 + acc_term;
                sm_read_addr[2] = 0 + r0*4 + acc_term;
                sm_read_addr[3] = 0 + r0*4 + acc_term;

                if (r1 >= 0) begin
                    sm_read_addr[4] = 0 + r1*4 + acc_term;
                    sm_read_addr[5] = 0 + r1*4 + acc_term;
                    sm_read_addr[6] = 0 + r1*4 + acc_term;
                    sm_read_addr[7] = 0 + r1*4 + acc_term;
                end else begin
                    sm_read_addr[4] = 0;
                    sm_read_addr[5] = 0;
                    sm_read_addr[6] = 0;
                    sm_read_addr[7] = 0;
                end

                @(posedge clk); #1;
                load_all(4'd0,
                    sm_read_data[0], sm_read_data[1],
                    sm_read_data[2], sm_read_data[3],
                    sm_read_data[4], sm_read_data[5],
                    sm_read_data[6], sm_read_data[7]);

                // ── Step 2: load B elements ───────────────────
                // Each core picks its own column of B
                sm_read_addr[0] = 8 + acc_term*2 + 0;
                sm_read_addr[1] = 8 + acc_term*2 + 1;
                sm_read_addr[2] = 8 + acc_term*2 + 1;
                sm_read_addr[3] = 8 + acc_term*2 + 1;
                sm_read_addr[4] = 8 + acc_term*2 + 0;
                sm_read_addr[5] = 8 + acc_term*2 + 1;
                sm_read_addr[6] = 8 + acc_term*2 + 1;
                sm_read_addr[7] = 8 + acc_term*2 + 1;

                @(posedge clk); #1;
                load_all(4'd1,
                    sm_read_data[0], sm_read_data[1],
                    sm_read_data[2], sm_read_data[3],
                    sm_read_data[4], sm_read_data[5],
                    sm_read_data[6], sm_read_data[7]);

                // ── Step 3: multiply-accumulate ───────────────
                // acc_mode 01 = set (first term), 10 = accumulate
                if (acc_term == 0)
                    run_one_instr(16'b1011_0010_0000_0001, 2'b01);
                else
                    run_one_instr(16'b1011_0010_0000_0001, 2'b10);
                @(posedge clk); #1;
            end

            // ── Collect results from accumulators ────────────
            for (ci = 0; ci < 2; ci = ci + 1) begin
                case (ci)
                    0: mat_c[r0][0] = acc_bus[0];
                    1: mat_c[r0][1] = acc_bus[1];
                endcase
                if (r1 >= 0) begin
                    case (ci)
                        0: mat_c[r1][0] = acc_bus[4];
                        1: mat_c[r1][1] = acc_bus[5];
                    endcase
                end
            end

            // ── Write C rows back to shared memory ───────────
            for (ci = 0; ci < 2; ci = ci + 1) begin
                case (ci)
                    0: sm_write(16+r0*2+0, mat_c[r0][0]);
                    1: sm_write(16+r0*2+1, mat_c[r0][1]);
                endcase
                if (r1 >= 0) begin
                    case (ci)
                        0: sm_write(16+r1*2+0, mat_c[r1][0]);
                        1: sm_write(16+r1*2+1, mat_c[r1][1]);
                    endcase
                end
            end
        end
    endtask

    // ── Main test sequence ────────────────────────────────────
    initial begin
        $dumpfile("matrix_multiply.vcd");
        $dumpvars(0, matrix_multiply_demo);

        // Initialise all signals
        reset=1; start=0; instr_valid_in=0;
        acc_ctrl_in=2'b00; load_en_bus=8'h00;
        load_addr=0; instruction_in=0;
        sm_write_en_bus=8'h00;
        for (i=0; i<8; i=i+1) begin
            load_data_bus[i]=0;
            sm_write_addr[i]=0;
            sm_write_data[i]=0;
            sm_read_addr[i]=0;
        end

        repeat(4) @(posedge clk);
        reset=0; @(posedge clk);

        // ── Inline matrix values (generated by Python) ────────
        // Matrix A
        mat_a[0][0] = 1;
        mat_a[0][1] = 4;
        mat_a[0][2] = 5;
        mat_a[0][3] = 6;
        mat_a[1][0] = 7;
        mat_a[1][1] = 7;
        mat_a[1][2] = 7;
        mat_a[1][3] = 7;

        // Matrix B
        mat_b[0][0] = 5;
        mat_b[0][1] = 5;
        mat_b[1][0] = 6;
        mat_b[1][1] = 4;
        mat_b[2][0] = 5;
        mat_b[2][1] = 2;
        mat_b[3][0] = 7;
        mat_b[3][1] = 5;

        $display("============================================");
        $display("  Mini GPU  -  2x4 x 4x2 Matrix Multiply");
        $display("  C = A x B  (parallel, 8 GPU cores)");
        $display("============================================");

        $display("\nMatrix A (2x4):");
        $display("  [%0d %0d %0d %0d]", mat_a[0][0], mat_a[0][1], mat_a[0][2], mat_a[0][3]);
        $display("  [%0d %0d %0d %0d]", mat_a[1][0], mat_a[1][1], mat_a[1][2], mat_a[1][3]);

        $display("\nMatrix B (4x2):");
        $display("  [%0d %0d]", mat_b[0][0], mat_b[0][1]);
        $display("  [%0d %0d]", mat_b[1][0], mat_b[1][1]);
        $display("  [%0d %0d]", mat_b[2][0], mat_b[2][1]);
        $display("  [%0d %0d]", mat_b[3][0], mat_b[3][1]);

        $display("--------------------------------------------");

        // ── Load A into shared memory ─────────────────────────
        sm_write(0+0*K+0, mat_a[0][0]);
        sm_write(0+0*K+1, mat_a[0][1]);
        sm_write(0+0*K+2, mat_a[0][2]);
        sm_write(0+0*K+3, mat_a[0][3]);
        sm_write(0+1*K+0, mat_a[1][0]);
        sm_write(0+1*K+1, mat_a[1][1]);
        sm_write(0+1*K+2, mat_a[1][2]);
        sm_write(0+1*K+3, mat_a[1][3]);

        // ── Load B into shared memory ─────────────────────────
        sm_write(8+0*N+0, mat_b[0][0]);
        sm_write(8+0*N+1, mat_b[0][1]);
        sm_write(8+1*N+0, mat_b[1][0]);
        sm_write(8+1*N+1, mat_b[1][1]);
        sm_write(8+2*N+0, mat_b[2][0]);
        sm_write(8+2*N+1, mat_b[2][1]);
        sm_write(8+3*N+0, mat_b[3][0]);
        sm_write(8+3*N+1, mat_b[3][1]);

        $display("Matrices loaded. Running GPU...");
        t_start = $time;

        // ── Dispatch computation batches ──────────────────────
        compute_rows(0, 1);  // rows 0 and 1

        t_end = $time;
        total_cycles = (t_end - t_start) / 10;

        $display("\nMatrix C = A x B (2x2):");
        $display("  [%3d %3d]", mat_c[0][0], mat_c[0][1]);
        $display("  [%3d %3d]", mat_c[1][0], mat_c[1][1]);

        // ── Software verification (inline) ────────────────────
        begin : verify
            integer correct;
            integer exp;
            correct = 1;
            for (i=0; i<2; i=i+1) begin
                for (j=0; j<2; j=j+1) begin
                    exp = 0;
                    for (k=0; k<4; k=k+1)
                        exp = exp + mat_a[i][k] * mat_b[k][j];
                    ref_c[i][j] = exp[7:0];
                    if (mat_c[i][j] !== ref_c[i][j]) begin
                        $display("  MISMATCH C[%0d][%0d]: got=%0d expected=%0d",
                                 i, j, mat_c[i][j], ref_c[i][j]);
                        correct = 0;
                    end
                end
            end
            if (correct) $display("  ALL ELEMENTS MATCH  (GPU == Reference)");
        end

        $display("\nGPU cycles: %0d", total_cycles);

        // ── Write result file ─────────────────────────────────
        file_handle = $fopen("matrix_result.hex", "w");
        if (file_handle != 0) begin
            $fwrite(file_handle, "# Matrix A\n");
            $fwrite(file_handle, "%0d,%0d,%0d,%0d\n", mat_a[0][0],mat_a[0][1],mat_a[0][2],mat_a[0][3]);
            $fwrite(file_handle, "%0d,%0d,%0d,%0d\n", mat_a[1][0],mat_a[1][1],mat_a[1][2],mat_a[1][3]);
            $fwrite(file_handle, "# Matrix B\n");
            $fwrite(file_handle, "%0d,%0d\n", mat_b[0][0],mat_b[0][1]);
            $fwrite(file_handle, "%0d,%0d\n", mat_b[1][0],mat_b[1][1]);
            $fwrite(file_handle, "%0d,%0d\n", mat_b[2][0],mat_b[2][1]);
            $fwrite(file_handle, "%0d,%0d\n", mat_b[3][0],mat_b[3][1]);
            $fwrite(file_handle, "# Matrix C\n");
            $fwrite(file_handle, "%0d,%0d\n", mat_c[0][0],mat_c[0][1]);
            $fwrite(file_handle, "%0d,%0d\n", mat_c[1][0],mat_c[1][1]);
            $fwrite(file_handle, "# Reference\n");
            $fwrite(file_handle, "%0d,%0d\n", ref_c[0][0],ref_c[0][1]);
            $fwrite(file_handle, "%0d,%0d\n", ref_c[1][0],ref_c[1][1]);
            $fwrite(file_handle, "cycles,%0d\n", total_cycles);
            $fwrite(file_handle, "# dims,2,4,2\n");
            $fclose(file_handle);
        end

        $finish;
    end

endmodule
